# Site settings
title: 记录者
email: fshuizhe@163.com
description: > # this means to ignore newlines until "baseurl:"
  收藏我写的文章，以及在网上搜集的有趣东西。
baseurl: # the subpath of your site, e.g. /blog/
url: "https://fshuizhe.github.io/weimin" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' or 'collection' as filter in sidebar.
filter: 'tag'
filt: 'collection'



defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "fshuizhe"
      permalink: /:title/

collections:
  jx: #剑侠
    output: true
    permalink: /:title/
  wenzi: #文字
    output: true
    permalink: /:title/

# Social account
# twitter:  username
# weibo:    ID
# github:   username
# codepen:  username
# dribbble: username

# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
